# `paulis` validation

In [1]:
%load_ext autoreload
%autoreload 1
%aimport rqutils.paulis

In [2]:
import numpy as np

## `paulis.paulis`

In [3]:
rqutils.paulis.paulis(2)

array([[[ 1.+0.j,  0.+0.j],
        [ 0.+0.j,  1.+0.j]],

       [[ 0.+0.j,  1.+0.j],
        [ 1.+0.j,  0.+0.j]],

       [[ 0.+0.j,  0.-1.j],
        [ 0.+1.j,  0.+0.j]],

       [[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]])

In [4]:
rqutils.paulis.paulis((2, 2))

array([[[[ 0.5+0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
         [ 0. +0.j ,  0.5+0.j ,  0. +0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0.5+0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5+0.j ]],

        [[ 0. +0.j ,  0.5+0.j ,  0. +0.j ,  0. +0.j ],
         [ 0.5+0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5+0.j ],
         [ 0. +0.j ,  0. +0.j ,  0.5+0.j ,  0. +0.j ]],

        [[ 0. +0.j ,  0. -0.5j,  0. +0.j ,  0. +0.j ],
         [ 0. +0.5j,  0. +0.j ,  0. +0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. -0.5j],
         [ 0. +0.j ,  0. +0.j ,  0. +0.5j,  0. +0.j ]],

        [[ 0.5+0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
         [ 0. +0.j , -0.5+0.j ,  0. +0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0.5+0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0. +0.j , -0.5+0.j ]]],


       [[[ 0. +0.j ,  0. +0.j ,  0.5+0.j ,  0. +0.j ],
         [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5+0.j ],


In [5]:
rqutils.paulis.paulis(3)

array([[[ 0.81649658+0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.81649658+0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.81649658+0.j]],

       [[ 0.        +0.j,  1.        +0.j,  0.        +0.j],
        [ 1.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j]],

       [[ 0.        +0.j,  0.        -1.j,  0.        +0.j],
        [ 0.        +1.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j]],

       [[ 1.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j, -1.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j]],

       [[ 0.        +0.j,  0.        +0.j,  1.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 1.        +0.j,  0.        +0.j,  0.        +0.j]],

       [[ 0.        +0.j,  0.        +0.j,  0.        -1.j],
        [ 0.  

## `paulis.components`

In [6]:
basis = rqutils.paulis.paulis((2, 2))
components = np.arange(1, 17).reshape((4, 4))
matrix = np.tensordot(basis, components, ((0, 1), (0, 1)))
rqutils.paulis.components(matrix, dim=(2, 2))

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j],
       [13.+0.j, 14.+0.j, 15.+0.j, 16.+0.j]])

## `paulis.compose`

In [7]:
rqutils.paulis.compose(components, dim=(2, 2)) == matrix

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## `paulis.l0_projector`

In [8]:
v = rqutils.paulis.l0_projector(2, 4)
manual = np.array([np.sqrt(2 / 4)] + [0.] * 7 + [np.sqrt(2 / 6)] + [0.] * 6 + [np.sqrt(2 / 12)])
np.allclose(v, manual)

True

## `paulis.truncate`

In [9]:
components = np.arange(1, 10)

matrix = rqutils.paulis.compose(components, dim=3)
submatrix = matrix[:2, :2]
subcomponents = rqutils.paulis.components(submatrix, dim=2)

np.allclose(rqutils.paulis.truncate(components, 2), subcomponents)

True

In [10]:
np.repeat([0, 1, 3, 4], 2)

array([0, 0, 1, 1, 3, 3, 4, 4])

In [11]:
components = np.arange(1, 82).reshape((9, 9))

matrix = rqutils.paulis.compose(components, dim=(3, 3))
indices = (np.repeat([0, 1, 3, 4], 4), np.tile([0, 1, 3, 4], 4))
submatrix = matrix[indices].reshape(4, 4)
subcomponents = rqutils.paulis.components(submatrix, dim=(2, 2))

np.allclose(rqutils.paulis.truncate(components, (2, 2)), subcomponents)

True

## `paulis.symmetry`

In [12]:
rqutils.paulis.symmetry(3)

array([ 0,  1, -1,  0,  1, -1,  1, -1,  0])

## `paulis.labels`

In [13]:
labels = rqutils.paulis.labels(3)
for label in labels:
    print(label)

\lambda_{0}
\lambda_{1}
\lambda_{2}
\lambda_{3}
\lambda_{4}
\lambda_{5}
\lambda_{6}
\lambda_{7}
\lambda_{8}


In [14]:
rqutils.paulis.labels((3, 3), symbol='', delimiter=',')

array([['\\frac{0,0}{2}', '\\frac{0,1}{2}', '\\frac{0,2}{2}',
        '\\frac{0,3}{2}', '\\frac{0,4}{2}', '\\frac{0,5}{2}',
        '\\frac{0,6}{2}', '\\frac{0,7}{2}', '\\frac{0,8}{2}'],
       ['\\frac{1,0}{2}', '\\frac{1,1}{2}', '\\frac{1,2}{2}',
        '\\frac{1,3}{2}', '\\frac{1,4}{2}', '\\frac{1,5}{2}',
        '\\frac{1,6}{2}', '\\frac{1,7}{2}', '\\frac{1,8}{2}'],
       ['\\frac{2,0}{2}', '\\frac{2,1}{2}', '\\frac{2,2}{2}',
        '\\frac{2,3}{2}', '\\frac{2,4}{2}', '\\frac{2,5}{2}',
        '\\frac{2,6}{2}', '\\frac{2,7}{2}', '\\frac{2,8}{2}'],
       ['\\frac{3,0}{2}', '\\frac{3,1}{2}', '\\frac{3,2}{2}',
        '\\frac{3,3}{2}', '\\frac{3,4}{2}', '\\frac{3,5}{2}',
        '\\frac{3,6}{2}', '\\frac{3,7}{2}', '\\frac{3,8}{2}'],
       ['\\frac{4,0}{2}', '\\frac{4,1}{2}', '\\frac{4,2}{2}',
        '\\frac{4,3}{2}', '\\frac{4,4}{2}', '\\frac{4,5}{2}',
        '\\frac{4,6}{2}', '\\frac{4,7}{2}', '\\frac{4,8}{2}'],
       ['\\frac{5,0}{2}', '\\frac{5,1}{2}', '\\frac{5,2}{2}',
   

In [15]:
rqutils.paulis.labels((2, 4), fmt='text')

array([['Iλ0/2', 'Iλ1/2', 'Iλ2/2', 'Iλ3/2', 'Iλ4/2', 'Iλ5/2', 'Iλ6/2',
        'Iλ7/2', 'Iλ8/2', 'Iλ9/2', 'Iλ10/2', 'Iλ11/2', 'Iλ12/2',
        'Iλ13/2', 'Iλ14/2', 'Iλ15/2'],
       ['Xλ0/2', 'Xλ1/2', 'Xλ2/2', 'Xλ3/2', 'Xλ4/2', 'Xλ5/2', 'Xλ6/2',
        'Xλ7/2', 'Xλ8/2', 'Xλ9/2', 'Xλ10/2', 'Xλ11/2', 'Xλ12/2',
        'Xλ13/2', 'Xλ14/2', 'Xλ15/2'],
       ['Yλ0/2', 'Yλ1/2', 'Yλ2/2', 'Yλ3/2', 'Yλ4/2', 'Yλ5/2', 'Yλ6/2',
        'Yλ7/2', 'Yλ8/2', 'Yλ9/2', 'Yλ10/2', 'Yλ11/2', 'Yλ12/2',
        'Yλ13/2', 'Yλ14/2', 'Yλ15/2'],
       ['Zλ0/2', 'Zλ1/2', 'Zλ2/2', 'Zλ3/2', 'Zλ4/2', 'Zλ5/2', 'Zλ6/2',
        'Zλ7/2', 'Zλ8/2', 'Zλ9/2', 'Zλ10/2', 'Zλ11/2', 'Zλ12/2',
        'Zλ13/2', 'Zλ14/2', 'Zλ15/2']], dtype='<U7')